# links
[WEB_BULLET]
	LAUNCH_URL="www.mplayer.com/cgi-bin/mplayer-set-up.sh?distribution=289"
	DIALOG_TITLE="Play Warzone 2100 on mplayer.com!"

	VENDOR_PROMO_CODE="289"
	TABLE="MPLAYNOW"
[MPLAYNOW]
	INSTALL_TYPE=RICE
